## Properties file for the SlidingWindowSubsciptionHandler deployment.
## Creator: ntt@mipl,jpl.nasa.gov
## Date: May 25, 2011
## Version: $Id: slidingWindowHandler.props,v 1.1 2011/05/25 22:18:47 ntt Exp $

# Declaration and description of properties:
#
# ** Property: disk.soft.limit
# -- Description: Indicates the amount of disk space, which, when 
# crossed, triggers a cleanup of older file content from the client.   
# NOTE: This is not a hard-maximum, as only when it is exceeded
# will a cleanup be performed.
# -- Type: number of megabytes (MB) (long)
# -- Required: Yes
#
# ** Property: disk.total.space
# -- Description: Indicates the total amount of space on the partition.
# NOTE: This property is a work around while waiting for Java 6.0 to 
# be adopted, as it contains file disk methods for ascertaining this
# information within the system.
# -- Type: number of megabytes (MB) (long)
# -- Required: Yes
#
# ** Property: disk.cleanup.ratio
# -- Description: Ratio of the used disk space to be freed during a 
# cleanup, so that old  files will be removed until the sum of the 
# filesize just reaches or passes (ratio * maxUsage).  
# Default: 0.25 (25%)
# -- Type: Ratio, between 0.0 and 1.0 (float)
# -- Required: No
#
# ** Property: prune.empty.directories
# -- Description: Informs handler that it should remove directories if,
# during cleanup, they become empty.  This effect cascades up the parent
# directory path until a non-empty directory is encountered. Default: 
# false.
# -- Type: true/false
# -- Required: No
#
# ** Property: preserve.newer.files
# -- Description: Informs handler that it should delete files if
# during cleanup, their client-based modification time is not 
# newer than the recorded value. This allows files that are updated
# since download to be preserved during cleanup. Default: false. 
# -- Type: true/false
# -- Required: No
# 
# ** Property: query.batch.size
# -- Description: During a cleanup operation, it is possible for a large
# number of files to be queried.  The value of this property indicates 
# how many files should be queried for each iteration, until cleanup
# frees enough disk space.  Default: 50
# -- Type: count (int)
# -- Required: No
#
# ** Property: log.cleanup.messages
# -- Description: During a cleanup operation, this option determines
# whether we will print a message to the log at the INFO level when
# a file is being deleted.  Default: true
# -- Type: boolean
# -- Required: No
#
# ** Property: slidingwindow.database.implementation
# -- Description: Indicates the fully-qualified class name of the 
# implementation of the SlidingWindowFileDatabase interface used by the
# deployment.  Class must be discoverable via the system classpath.
# -- Type: Fully-qualified class (string)
# -- Required: Yes
#
# ** Property: database.properties.location
# -- Description: Indicates the location of database properties file.
# This properties file will be parsed and used by the database.
# -- Type: Filepath (string)
# -- Required: Dependent upon database implementation
#


# Implementation of the MSLFileDatabase interface
slidingwindow.database.implementation=jpl.mipl.mdms.FileService.komodo.client.handlers.examples.slidingwindow.SlidingWindowDerbyFileDatabase

# The soft limit is a point which, when passed, triggers a cleanup
disk.soft.limit=1024000000

# The ratio indicates the size of the window of older files that will be deleted ( * soft.limit)
disk.cleanup.ratio=.25



