# DEV krb5.conf
[realms]
        MIPS-DEV.JPL.NASA.GOV = {
                kdc = ham.jpl.nasa.gov:88
                admin_server = ham.jpl.nasa.gov
                default_domain = jpl.nasa.gov
        }
 
[domain_realm]
        .jpl.nasa.gov = MIPS-DEV.JPL.NASA.GOV
        jpl.nasa.gov = MIPS-DEV.JPL.NASA.GOV
 
[libdefaults]
        ticket_lifetime = 600
        default_domain = MIPS-DEV.JPL.NASA.GOV
        default_realm = MIPS-DEV.JPL.NASA.GOV
#       default_tkt_enctypes = des-cbc-crc des3-hmac-sha1
#       default_tgs_enctypes = des-cbc-crc des3-hmac-sha1
 
[logging]
        kdc = FILE:/var/log/krb5kdc.log
        admin_server = FILE:/var/log/kadmin.log
        DEFault = FILE:/var/log/krb5lib.log

